general:
  seed: 42
  wandb: True
  ddp: False
  ncpus: 8
  gpus: 0
  world_size: 2
  rank: 0
  device: "cuda"
  preprocess: False
  load_trained_model_for_testing: False 

dataset:
  path_to_data: "/groups/claytonm/gauravs_data/clevrmath_data/data"
  get_image_tensors: True
  shuffle: True
  vocab_freq: 5
  num_workers: 0
  pin_memory: False
  image_width: 480
  image_height: 320

training:
  general:
    clip: 1 
    batch_size: 32
    epochs: 10
    dropout: 0.30000000000000004
    learning_rate:  0.0005334026654546251
    weight_decay: 0.00021519277485609046
    betas: [0.6,0.6]
    early_stopping: 8
    num_classes: 11
  
  scheduler:
    isScheduler: False
    verbose: True
    scheduler_step_size: 2
    scheduler_gamma: 0.5
  
  adaptor:
    finetune: True
    features: [512,256,128,64]

  roberta:
    in_dim: 768
    finetune: False

  clip:
    finetune: True
    configuration: 
      hidden_size: 128
      intermediate_size: 256
      projection_dim: 384
      num_hidden_layers: 7
      num_attention_heads: 4
      num_channels: 3
      image_size: 224
      patch_size: 32
