general:
  seed: 42
  wandb: False
  ddp: False
  ncpus: 8
  gpus: 0
  world_size: 2
  rank: 0
  device: "cpu"
  preprocess: False
  load_trained_model_for_testing: False 

dataset:
  path_to_data: "/groups/claytonm/gauravs_data/clevrmath_data/data"
  get_image_tensors: True
  shuffle: True
  vocab_freq: 5
  num_workers: 4
  pin_memory: False
  image_width: 480
  image_height: 320

training:
  general:
    clip: 1 
    batch_size: 10
    epochs: 1
    dropout: 0.1
    learning_rate: 0.0001
    weight_decay: 0.00001
    betas: [0.9,0.999]
    early_stopping: 5
    scheduler_step_size: 50
    scheduler_gamma: 0.5

  unet_encoder: 
    input_channels: 4
    features: [64, 128, 256, 512]
