general:
  seed: 42
  wandb: True
  ddp: False
  ncpus: 8
  gpus: 0
  world_size: 2
  rank: 0
  device: "cuda"
  preprocess: False
  load_trained_model_for_testing: False 

dataset:
  path_to_data: "/groups/claytonm/gauravs_data/clevrmath_data/data"
  get_image_tensors: True
  shuffle: True
  vocab_freq: 5
  num_workers: 0
  pin_memory: False
  image_width: 480
  image_height: 320

training:
  general:
    clip: 1 
    batch_size: 16
    epochs: 50
    dropout: 0.2
    learning_rate: 0.0005
    weight_decay: 0.00001
    betas: [0.9,0.8]
    early_stopping: 3
    num_classes: 11
  
  scheduler:
    isScheduler: True
    verbose: True
    scheduler_step_size: 50
    scheduler_gamma: 0.5
  
  adaptor:
    in_dim: 768
    features: [512,256,128,64]
